package vista;

import controlador.ControladorArchivoBinInves;
import controlador.ControladorArchivoBinarioMues;
import controlador.ControladorArchivoBinarioPatron;
import controlador.ControladorAsignacion;
import java.util.ArrayList;





import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import modelos.investigador;
import modelos.muestras;
import modelos.patrones;

/**
 *
 * @author cardo
 */
public class modAdmin extends javax.swing.JFrame {

    /**
     * Creates new form modAdmin
     */
    public modAdmin() {
        initComponents();
        refrescarTabla();//refresca la tabla de investigadores
        refrescarTabla2();//refresca la tabla de muestras
        refrescarTablaPatrones();//refresca la tabla de patrones
      
    
        
        //llenan mis comboboxes
        ControladorAsignacion controladorAsignacion = new ControladorAsignacion();
        controladorAsignacion.cargarComboBoxes(comboInves, comboMues);
        
    }
    
    //metodo para crear investigadores y para resfrescar la tabla de investigadores
    public void refrescarTabla() {
    ControladorArchivoBinInves archivoBinario = new ControladorArchivoBinInves();
    ArrayList<investigador> investigadores = archivoBinario.obtenerContenido("investigador.bin");
    DefaultTableModel tablaModelo = (DefaultTableModel) jTable1.getModel();
    tablaModelo.setRowCount(0);
    for (investigador invest : investigadores) {
        tablaModelo.addRow(new Object[]{
            invest.getCodigo(), invest.getNombre(), invest.getGenero(), invest.getExperimento()});

    }
}

    
    //metodo para refrescar la tabla de muestras
    public void refrescarTabla2() {
        ControladorArchivoBinarioMues archivoBinarioMues = new ControladorArchivoBinarioMues();
        ArrayList<muestras> muestras = archivoBinarioMues.obtenerContenidoMues("muestras.bin");

        DefaultTableModel tablaModeloMues = (DefaultTableModel) jTable2.getModel();
        tablaModeloMues.setRowCount(0); 
        for (muestras mues : muestras) {
            tablaModeloMues.addRow(new Object[]{mues.getCodigo(), mues.getDescripcion(), mues.getEstado(), "ver"});
 
        }
        TableColumn columnaAcciones = jTable2.getColumnModel().getColumn(3);
        columnaAcciones.setCellRenderer(new RenderBttnVerMues());
        columnaAcciones.setCellEditor(new RenderBttnVerMues());
    }

        
        
    // Método para refrescar la tabla de patrones
    public void refrescarTablaPatrones() {
        ControladorArchivoBinarioPatron archivoBinarioPatrones = new ControladorArchivoBinarioPatron();
        ArrayList<patrones> patrones = archivoBinarioPatrones.obtenerContenidoPatrones("patrones.bin");

        DefaultTableModel tablaModelo = (DefaultTableModel) jTable3.getModel();
        tablaModelo.setRowCount(0); 
        for (patrones patron : patrones) {
            tablaModelo.addRow(new Object[]{patron.getCodigo(), patron.getNombre(), "Ver"});
        }

        TableColumn columnaAcciones = jTable3.getColumnModel().getColumn(2);
        columnaAcciones.setCellRenderer(new RenderBttnVerPatron());
        columnaAcciones.setCellEditor(new RenderBttnVerPatron());
    }


        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bttnCrearInv = new javax.swing.JButton();
        bttnCargarInv = new javax.swing.JButton();
        bttnActualizarInv = new javax.swing.JButton();
        bttnEliminarInv = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bttnCrearMu = new javax.swing.JButton();
        bttnCargarMu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboInves = new javax.swing.JComboBox<>();
        comboMues = new javax.swing.JComboBox<>();
        bttnAsigExp = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        bttnCrearP = new javax.swing.JButton();
        bttnCargarP = new javax.swing.JButton();
        bttnEliminarP = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        bttnCerrarModAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Género", "Experimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bttnCrearInv.setText("Crear");
        bttnCrearInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCrearInvActionPerformed(evt);
            }
        });

        bttnCargarInv.setText("Cargar");
        bttnCargarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCargarInvActionPerformed(evt);
            }
        });

        bttnActualizarInv.setText("Actualizar");
        bttnActualizarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnActualizarInvActionPerformed(evt);
            }
        });

        bttnEliminarInv.setText(" Eliminar");
        bttnEliminarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEliminarInvActionPerformed(evt);
            }
        });

        jButton1.setText("Refrescar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bttnCrearInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnActualizarInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bttnEliminarInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnCargarInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttnCrearInv)
                            .addComponent(bttnCargarInv))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttnActualizarInv)
                            .addComponent(bttnEliminarInv))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Investigadores", jPanel1);

        bttnCrearMu.setText("Crear");
        bttnCrearMu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCrearMuActionPerformed(evt);
            }
        });

        bttnCargarMu.setText("Cargar");
        bttnCargarMu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCargarMuActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripción", "Estado", "Acciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton2.setText("refrescar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bttnCrearMu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnCargarMu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(75, 75, 75))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bttnCrearMu)
                        .addGap(30, 30, 30)
                        .addComponent(bttnCargarMu)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2)))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Muestras", jPanel2);

        jLabel1.setText("Investigador");

        jLabel2.setText("Muestra");

        comboInves.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboInves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboInvesActionPerformed(evt);
            }
        });

        comboMues.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMuesActionPerformed(evt);
            }
        });

        bttnAsigExp.setText("Asignar");
        bttnAsigExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAsigExpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboMues, 0, 125, Short.MAX_VALUE)
                            .addComponent(comboInves, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(bttnAsigExp)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboInves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboMues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(bttnAsigExp)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Asignacion de Experimentos", jPanel3);

        bttnCrearP.setText("Crear");
        bttnCrearP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCrearPActionPerformed(evt);
            }
        });

        bttnCargarP.setText("Cargar");
        bttnCargarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCargarPActionPerformed(evt);
            }
        });

        bttnEliminarP.setText("Eliminar");
        bttnEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEliminarPActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Acciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton3.setText("refrescar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnCrearP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttnCargarP))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(bttnEliminarP)))
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttnCrearP)
                            .addComponent(bttnCargarP))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttnEliminarP)
                            .addComponent(jButton3))))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Patrones", jPanel4);

        bttnCerrarModAdmin.setText("Cerrar sesión");
        bttnCerrarModAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCerrarModAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(446, 446, 446)
                        .addComponent(bttnCerrarModAdmin)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(bttnCerrarModAdmin)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboInvesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboInvesActionPerformed
     


    }//GEN-LAST:event_comboInvesActionPerformed

    private void bttnCrearInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCrearInvActionPerformed
        // TODO add your handling code here:
        
        CrearInves CInv = new CrearInves();
        CInv.setLocationRelativeTo(null);
        CInv.setVisible(true);
        
     
    }//GEN-LAST:event_bttnCrearInvActionPerformed

    private void bttnCargarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCargarInvActionPerformed
        // TODO add your handling code here:
        
       
    ControladorArchivoBinInves controlador = new ControladorArchivoBinInves();
    String rutaCSV = "C:\\Users\\cardo\\OneDrive\\Escritorio\\baseInves.csv"; //la ruta del csv a cargar a diferencia de las muestras y patrones esta ruta no la puse en mis controladores
    String rutaBinario = "investigador.bin";//ruta del .bin de mis investigadores
    controlador.leerCSV(rutaCSV, rutaBinario);
    refrescarTabla();
    JOptionPane.showMessageDialog(this, "Datos cargados exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);

        
        
        
    }//GEN-LAST:event_bttnCargarInvActionPerformed

    private void bttnEliminarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEliminarInvActionPerformed
        // TODO add your handling code here:
        
        eliminarInves EliInv = new eliminarInves();
        EliInv.setLocationRelativeTo(null);
        EliInv.setVisible(true);
        
        
    }//GEN-LAST:event_bttnEliminarInvActionPerformed

    private void bttnActualizarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnActualizarInvActionPerformed
        // TODO add your handling code here:
        
        actualizarInves AcInves = new actualizarInves();
        AcInves.setLocationRelativeTo(null);
        AcInves.setVisible(true);
        
        
        
    }//GEN-LAST:event_bttnActualizarInvActionPerformed

    private void bttnCrearMuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCrearMuActionPerformed
        // TODO add your handling code here:
        
        crearMuestra CrearM = new  crearMuestra();
        CrearM.setLocationRelativeTo(null);
        CrearM.setVisible(true);
        
                
                
        
        
    }//GEN-LAST:event_bttnCrearMuActionPerformed

    private void bttnCerrarModAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCerrarModAdminActionPerformed
        // TODO add your handling code here:
        
        modUsuario MUsu = new modUsuario();
        MUsu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttnCerrarModAdminActionPerformed

    private void bttnCrearPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCrearPActionPerformed
        // TODO add your handling code here:
        
        crearPatron creaP = new crearPatron();
        creaP.setLocationRelativeTo(null);
        creaP.setVisible(true);
        

    }//GEN-LAST:event_bttnCrearPActionPerformed

    private void bttnCargarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCargarPActionPerformed
        // TODO add your handling code here:
        
        ControladorArchivoBinarioPatron archivo = new ControladorArchivoBinarioPatron();
        archivo.leerCSV("patrones.bin");
        refrescarTablaPatrones();
        JOptionPane.showMessageDialog(null, "Patrones cargados correctanebte");
        

        
    }//GEN-LAST:event_bttnCargarPActionPerformed

    private void bttnEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEliminarPActionPerformed
        // TODO add your handling code here:
        
        eliminarPatron eliminarP = new eliminarPatron();
        eliminarP.setLocationRelativeTo(null);
        eliminarP.setVisible(true);
    }//GEN-LAST:event_bttnEliminarPActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        refrescarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        refrescarTabla2();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        refrescarTablaPatrones();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bttnCargarMuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCargarMuActionPerformed
    
        ControladorArchivoBinarioMues archivo = new ControladorArchivoBinarioMues();
        archivo.leerCSV("muestras.bin");
        refrescarTabla2();
        JOptionPane.showMessageDialog(null, "muestras cargados correctanebte");
        ControladorArchivoBinInves controlador = new ControladorArchivoBinInves();
        

        /*String rutaCSV = "C:\\Users\\cardo\\OneDrive\\Escritorio\\baseInves.csv";
        String rutaBinario = "investigador.bin";
        controlador.leerCSV(rutaCSV, rutaBinario);
        refrescarTabla();
        JOptionPane.showMessageDialog(this, "Datos cargados exitosamente", "Información", JOptionPane.INFORMATION_MESSAGE);*/
        
    }//GEN-LAST:event_bttnCargarMuActionPerformed

    private void comboMuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMuesActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_comboMuesActionPerformed

    private void bttnAsigExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAsigExpActionPerformed
        //asignador de experimentos
                                                  
    String codigoInvestigador = (String) comboInves.getSelectedItem();
    String codigoMuestra = (String) comboMues.getSelectedItem();
    
    if (codigoInvestigador == null || codigoMuestra == null) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un investigador y una muestra", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    ControladorAsignacion controladorAsignacion = new ControladorAsignacion();
    boolean asignacionExitosa = controladorAsignacion.asignarExperimento(codigoInvestigador, codigoMuestra);
    
    if (asignacionExitosa) {
        JOptionPane.showMessageDialog(this, "Experimento asignado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        refrescarTabla();
        refrescarTabla2();
        controladorAsignacion.cargarComboBoxes(comboInves, comboMues);
    } else {
        JOptionPane.showMessageDialog(this, "Error al asignar el experimento", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_bttnAsigExpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnActualizarInv;
    private javax.swing.JButton bttnAsigExp;
    private javax.swing.JButton bttnCargarInv;
    private javax.swing.JButton bttnCargarMu;
    private javax.swing.JButton bttnCargarP;
    private javax.swing.JButton bttnCerrarModAdmin;
    private javax.swing.JButton bttnCrearInv;
    private javax.swing.JButton bttnCrearMu;
    private javax.swing.JButton bttnCrearP;
    private javax.swing.JButton bttnEliminarInv;
    private javax.swing.JButton bttnEliminarP;
    private javax.swing.JComboBox<String> comboInves;
    private javax.swing.JComboBox<String> comboMues;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
