/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author cardo
 */
public class modAdmin extends javax.swing.JFrame {

    /**
     * Creates new form modAdmin
     */
    public modAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bttnCrearInv = new javax.swing.JButton();
        bttnCargarInv = new javax.swing.JButton();
        bttnActualizarInv = new javax.swing.JButton();
        bttnEliminarInv = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bttnCrearMu = new javax.swing.JButton();
        bttnCargarMu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        bttnAsigExp = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        bttnCrearP = new javax.swing.JButton();
        bttnCargarP = new javax.swing.JButton();
        bttnEliminarP = new javax.swing.JButton();
        bttnCerrarModAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Género", "Experimetno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bttnCrearInv.setText("Crear");
        bttnCrearInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCrearInvActionPerformed(evt);
            }
        });

        bttnCargarInv.setText("Cargar");
        bttnCargarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCargarInvActionPerformed(evt);
            }
        });

        bttnActualizarInv.setText("Actualizar");
        bttnActualizarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnActualizarInvActionPerformed(evt);
            }
        });

        bttnEliminarInv.setText(" Eliminar");
        bttnEliminarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEliminarInvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bttnCrearInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bttnCargarInv))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bttnActualizarInv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttnEliminarInv)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttnCrearInv)
                            .addComponent(bttnCargarInv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttnActualizarInv)
                            .addComponent(bttnEliminarInv))))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Investigadores", jPanel1);

        bttnCrearMu.setText("Crear");
        bttnCrearMu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCrearMuActionPerformed(evt);
            }
        });

        bttnCargarMu.setText("Cargar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(388, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttnCargarMu)
                    .addComponent(bttnCrearMu))
                .addGap(75, 75, 75))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(bttnCrearMu)
                .addGap(30, 30, 30)
                .addComponent(bttnCargarMu)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Muestras", jPanel2);

        jLabel1.setText("Investigador");

        jLabel2.setText("Muestra");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bttnAsigExp.setText("Asignar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(80, 80, 80)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(bttnAsigExp)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(bttnAsigExp)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Asignacion de Experimentos", jPanel3);

        bttnCrearP.setText("Crear");
        bttnCrearP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCrearPActionPerformed(evt);
            }
        });

        bttnCargarP.setText("Cargar");
        bttnCargarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCargarPActionPerformed(evt);
            }
        });

        bttnEliminarP.setText("Eliminar");
        bttnEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEliminarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(358, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(bttnCrearP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttnCargarP)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(bttnEliminarP)
                        .addGap(64, 64, 64))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnCrearP)
                    .addComponent(bttnCargarP))
                .addGap(18, 18, 18)
                .addComponent(bttnEliminarP)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Patrones", jPanel4);

        bttnCerrarModAdmin.setText("Cerrar sesión");
        bttnCerrarModAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCerrarModAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bttnCerrarModAdmin)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(bttnCerrarModAdmin)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void bttnCrearInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCrearInvActionPerformed
        // TODO add your handling code here:
        
        CrearInves CInv = new CrearInves();
        CInv.setLocationRelativeTo(null);
        CInv.setVisible(true);
        
    
        
        /*           void agregarContenido(String contenido, String ruta_archivo){
        
        
        try {
        FileWriter archivo = new FileWriter(ruta_archivo, true); // En el caso que no exista el archivo lo crea y si ya existe el archivo lo sobreescribe
        archivo.write(contenido + "\n");
        archivo.close();
        System.out.println("Contenido agregado correctamente");
        } catch (Exception e) {
        System.out.println(e);
        }
        }*/
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_bttnCrearInvActionPerformed

    private void bttnCargarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCargarInvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnCargarInvActionPerformed

    private void bttnEliminarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEliminarInvActionPerformed
        // TODO add your handling code here:
        
        eliminarInves EliInv = new eliminarInves();
        EliInv.setLocationRelativeTo(null);
        EliInv.setVisible(true);
        
        
    }//GEN-LAST:event_bttnEliminarInvActionPerformed

    private void bttnActualizarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnActualizarInvActionPerformed
        // TODO add your handling code here:
        
        actualizarInves AcInves = new actualizarInves();
        AcInves.setLocationRelativeTo(null);
        AcInves.setVisible(true);
        
        
        
    }//GEN-LAST:event_bttnActualizarInvActionPerformed

    private void bttnCrearMuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCrearMuActionPerformed
        // TODO add your handling code here:
        
        crearMuestra CrearM = new  crearMuestra();
        CrearM.setLocationRelativeTo(null);
        CrearM.setVisible(true);
        
                
                
        
        
    }//GEN-LAST:event_bttnCrearMuActionPerformed

    private void bttnCerrarModAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCerrarModAdminActionPerformed
        // TODO add your handling code here:
        
        modUsuario MUsu = new modUsuario();
        MUsu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttnCerrarModAdminActionPerformed

    private void bttnCrearPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCrearPActionPerformed
        // TODO add your handling code here:
        
        crearPatron creaP = new crearPatron();
        creaP.setLocationRelativeTo(null);
        creaP.setVisible(true);
        

    }//GEN-LAST:event_bttnCrearPActionPerformed

    private void bttnCargarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCargarPActionPerformed
        // TODO add your handling code here:
        

        
    }//GEN-LAST:event_bttnCargarPActionPerformed

    private void bttnEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEliminarPActionPerformed
        // TODO add your handling code here:
        
        eliminarPatron eliminarP = new eliminarPatron();
        eliminarP.setLocationRelativeTo(null);
        eliminarP.setVisible(true);
    }//GEN-LAST:event_bttnEliminarPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnActualizarInv;
    private javax.swing.JButton bttnAsigExp;
    private javax.swing.JButton bttnCargarInv;
    private javax.swing.JButton bttnCargarMu;
    private javax.swing.JButton bttnCargarP;
    private javax.swing.JButton bttnCerrarModAdmin;
    private javax.swing.JButton bttnCrearInv;
    private javax.swing.JButton bttnCrearMu;
    private javax.swing.JButton bttnCrearP;
    private javax.swing.JButton bttnEliminarInv;
    private javax.swing.JButton bttnEliminarP;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
